### ISSUE TITLE
SDK not recognized after installing through composer

### ISSUE THREAD

**Issue by JonPHenry** [Kucoin/kucoin-php-sdk#100]
Using Visual Studio 2019, I install the kucoin php api through composer but when running a simple server time test, I cant get it to recognize the library.  Keep getting 'Uncaught Error: Class 'KuCoin\SDK\PublicApi\Time' not found in C...

Steps:
1. New Visual Studio  php project
2. Install kucoin\kucoin-php-sdk using composer...ver 1.1.21 installs fine
3. Run simple time test

        `<?php
        
        use KuCoin\SDK\PublicApi\Time;
        
        $api = new Time();
        $timestamp = $api->timestamp();
        var_dump($timestamp);`

4. Run and get 'Uncaught Error: Class 'KuCoin\SDK\PublicApi\Time' not found in C...

When I change views and drill down, the time folder is there but the folder hierarchy is different. Are we supposed to manually change that for each file?

**Comment by mdabbagh-ir** [comment]
Hello
How did you solve this problem?

**Comment by tahola** [comment]
I have the same issue on Laravel :

> composer require kucoin/kucoin-php-sdk
> ./composer.json has been updated
> Running composer update kucoin/kucoin-php-sdk
> Loading composer repositories with package information
> Updating dependencies
> Nothing to modify in lock file
> Writing lock file
> Installing dependencies from lock file (including require-dev)
> Nothing to install, update or remove
> Generating autoload files
> 11 packages you are using are looking for funding.
> Use the `composer fund` command to find out more!
> No security vulnerability advisories found
> Using version ^1.1 for kucoin/kucoin-php-sdk

But nothing in composer.json and class not found, any idea ?

**Comment by ISAAC-XXYYZZ** [comment]
Please try updating to the latest version of the SDK and modify your code to try again. If you encounter any issues, feel free to provide feedback.
