### ISSUE TITLE
"Order size increment invalid" when using decimals.

### ISSUE THREAD

**Issue by mkmnstr123** [Kucoin/kucoin-php-sdk#102]
Hello,

So, I've been working for a while using the SDK and I noted that there is a problem when trying to use decimals. Also I noted this happens also in other of your libraries. Here is an example:

https://github.com/ccxt/ccxt/issues/1846#issuecomment-364370011

Also, in that thread it mentions a catalogue of valid decimal points, can you please provide it?

Thanks

Request:

```
{
   "clientOid":"60eb7238e742b",
   "size":"3258.921114",
   "symbol":"ADA-USDT",
   "type":"MARKET",
   "side":"sell",
   "timeInForce":"IOC"
}

```
Response:
`{"code":"400100","msg":"Order size increment invalid."}`

**Comment by RCTORONTO** [comment]
did you try restricting your size amount to three or four places to see if that works?

**Comment by meti0time** [comment]
"funds":"3258.921114"

**Comment by ISAAC-XXYYZZ** [comment]
Please refer to our documentation: https://www.kucoin.com/docs/rest/spot-trading/orders/place-order
> Size (Size)
When placing a limit order, size refers to the amount of trading targets (the asset name written in front) for the trading pair. Teh Size must be based on the [baseIncrement](https://www.kucoin.com/docs/rest/spot-trading/market-data/get-symbols-list) of the trading pair. The baseIncrement represents the precision for the trading pair. The size of an order must be a positive-integer multiple of baseIncrement and must be between baseMinSize and baseMaxSize.

>Funds (Funds)
When placing a market order, the funds field refers to the funds for the priced asset (the asset name written latter) of the trading pair. The funds must be based on the [quoteIncrement](https://www.kucoin.com/docs/rest/spot-trading/market-data/get-symbols-list) of the trading pair. The quoteIncrement represents the precision of the trading pair. The funds value for an order must be a multiple of quoteIncrement and must be between quoteMinSize and quoteMaxSize.

So use the following code to retrieve the information you need
``` php
$symbol->getListV2('BTC');
```
Please modify your code to try again. If you encounter any issues, feel free to provide feedback.
