### ISSUE TITLE
Class 'Kucoin\SDK\Auth' not found

### ISSUE THREAD

**Issue by inazeem** [Kucoin/kucoin-php-sdk#106]
I am trying api with laravel and i am getting the auth not found error. I have checked the directory and file is there. I am not sure why it is not picking up. Any help will be great. 

$auth = new Auth($this->api_key, $this->api_secret, $this->passphrase, Auth::API_KEY_VERSION_V2);

**Comment by hhxsv5** [comment]
Did you forget use namespace `use Kucoin\SDK\Auth;`?  Or try `composer dumpautoload`

**Comment by inazeem** [comment]
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use KuCoin\SDK\PublicApi\Time;
use KuCoin\SDK\PrivateApi\Account;
use KuCoin\SDK\Exceptions\HttpException;
use KuCoin\SDK\Exceptions\BusinessException;
use Kucoin\SDK\Auth;

So this is what I have on top of the controller class.

**Comment by hhxsv5** [comment]
There is a typo 'Kucoin', should be 'KuCoin'.

**Comment by inazeem** [comment]
Thanks, It worked!
