### ISSUE TITLE
Order remark

### ISSUE THREAD

**Issue by RCTORONTO** [Kucoin/kucoin-php-sdk#108]
"done" and "filled" order updates received via websocket feed do not contain the order remark.

**Comment by codewc** [comment]
The remark field is a non-transactional core field. Based on the consideration of delivery performance, this remark field is not included in the order push message

**Comment by RCTORONTO** [comment]
Our application uses the remark to store information about that orders previous one - to know if it's reciprocal or a new one, not including that one little tidbit of information means we will have to make an additional call to the API to retrieve it. NOT IDEAL.   Also "createdAt" should really remain "createdAt" throughout, when you start changing names of things I.E. "createdAt" suddenly becomes "orderTime" it's really makes for confusion.  It's pretty obvious this API and feed were written by different people at different times....

**Comment by codewc** [comment]
Brother, regarding the remark requirement mentioned, just like you said, you need to query it again through the API, or you can maintain the corresponding relationship with the database locally. This is very inconvenient, but remark will also take up network traffic, so after comprehensive consideration, we decided not to return remark in the message

Regarding the phenomenon that the fields are not uniform or easy to be confused, I think you make a lot of sense. It is necessary to avoid this situation in the future.

**Comment by codewc** [comment]
> Our application uses the remark to store information about that orders previous one - to know if it's reciprocal or a new one, not including that one little tidbit of information means we will have to make an additional call to the API to retrieve it. NOT IDEAL. Also "createdAt" should really remain "createdAt" throughout, when you start changing names of things I.E. "createdAt" suddenly becomes "orderTime" it's really makes for confusion. It's pretty obvious this API and feed were written by different people at different times....

Brother, regarding the remark requirement mentioned, just like you said, you need to query it again through the API, or you can maintain the corresponding relationship with the database locally. This is very inconvenient, but remark will also take up network traffic, so after comprehensive consideration, we decided not to return remark in the message

Regarding the phenomenon that the fields are not uniform or easy to be confused, I think you make a lot of sense. It is necessary to avoid this situation in the future.

**Comment by RCTORONTO** [comment]
alright, we'll sort it by a separate call to get order by clientOid... thanks for the reply

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
