### ISSUE TITLE
currency get detail on another chain

### ISSUE THREAD

**Issue by mahdi4187** [Kucoin/kucoin-php-sdk#109]
$detail = Kucoin::currency()->getDetail('ETH', 'KCC');

`
array:12 [▼
  "currency" => "ETH"
  "name" => "ETH"
  "fullName" => "Ethereum"
  "precision" => 8
  "confirms" => 1
  "contractAddress" => ""
  "withdrawalMinSize" => "0.01"
  "withdrawalMinFee" => "0.004"
  "isWithdrawEnabled" => true
  "isDepositEnabled" => true
  "isMarginEnabled" => true
  "isDebitEnabled" => true
]
`

$detail = Kucoin::currency()->getDetail('ETH');

`
array:12 [▼
  "currency" => "ETH"
  "name" => "ETH"
  "fullName" => "Ethereum"
  "precision" => 8
  "confirms" => 12
  "contractAddress" => ""
  "withdrawalMinSize" => "0.01"
  "withdrawalMinFee" => "0.004"
  "isWithdrawEnabled" => true
  "isDepositEnabled" => true
  "isMarginEnabled" => true
  "isDebitEnabled" => true
]
`

The withdrawalMinFee did not change

**Comment by codewc** [comment]
> $detail = Kucoin::currency()->getDetail('ETH', 'KCC');
> 
> `array:12 [▼ "currency" => "ETH" "name" => "ETH" "fullName" => "Ethereum" "precision" => 8 "confirms" => 1 "contractAddress" => "" "withdrawalMinSize" => "0.01" "withdrawalMinFee" => "0.004" "isWithdrawEnabled" => true "isDepositEnabled" => true "isMarginEnabled" => true "isDebitEnabled" => true ]`
> 
> $detail = Kucoin::currency()->getDetail('ETH');
> 
> `array:12 [▼ "currency" => "ETH" "name" => "ETH" "fullName" => "Ethereum" "precision" => 8 "confirms" => 12 "contractAddress" => "" "withdrawalMinSize" => "0.01" "withdrawalMinFee" => "0.004" "isWithdrawEnabled" => true "isDepositEnabled" => true "isMarginEnabled" => true "isDebitEnabled" => true ]`
> 
> The withdrawalMinFee did not change

Hi, The withdrawalMinFees is a returned configuration parameter. 
Is there any difference between your expected value and the actual return value?

**Comment by mahdi4187** [comment]
no withdrawalMinFees in kcc 0.001

but return  0.004

**Comment by hhxsv5** [comment]
try `$detail = Kucoin::currency()->getDetail('ETH', 'kcc')`

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
