### ISSUE TITLE
withdrawal applay error

### ISSUE THREAD

**Issue by mahdi4187** [Kucoin/kucoin-php-sdk#110]
hi

after set memo in send xrp

`[API]Failure: api code is NOT 200000, POST /api/v1/withdrawals with body={"clientOid":"6139b4edd27c27.88823947","currency":"XRP","address":"rDt7d2bf2CSKzTFug2etkhbr8yQjbZtLE7","memo":"25802","amount":21.2,"isInner":false,"chain":""}, respond code=400100 message="request parameter illegal" body={"code":"400100","msg":"request parameter illegal"}`

**Comment by codewc** [comment]
> /

Dear User,
Thank you for contacting us.
 
This error message is not very clear - "request parameter illegal"
The actual reason for the failure is that your deposit account balance is insufficient.
We will optimize the error message in the future.

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
