### ISSUE TITLE
Problem in market order

### ISSUE THREAD

**Issue by meti0time** [Kucoin/kucoin-php-sdk#111]
![image](https://user-images.githubusercontent.com/22997680/132963438-a21cc701-c5c3-47f6-bbd6-feac021d7184.png)

Why is no market order registered with this code?

**Comment by ISAAC-XXYYZZ** [comment]
Please refer to our documentation: https://www.kucoin.com/docs/rest/spot-trading/orders/place-order. 
Use create method with the "type" field set to market.
