### ISSUE TITLE
multiple deposits

### ISSUE THREAD

**Issue by pedram1995kzm** [Kucoin/kucoin-php-sdk#115]
hi
in this api i can only one address for each coin like BTC
so my users in website should have unique deposit address for BTC
otherwise how can I check who has deposit?
they all have same deposit address!

**Comment by codewc** [comment]
> hi in this api i can only one address for each coin like BTC so my users in website should have unique deposit address for BTC otherwise how can I check who has deposit? they all have same deposit address!
In this case, you can distinguish by `remark`

**Comment by pedram1995kzm** [comment]
tnx for response
I have a question
suppose some one wants to sent usdt from her tronlinkpro to her kucoin wallet
how can she set rermark
Tronlinkpro doesn't have this remark field in withdrawal form

**Comment by ISAAC-XXYYZZ** [comment]
Generally speaking, for a given coin under an account, a specific network corresponds to a single address. Our SDK is consistent with the product in this regard. I believe that if you have developed your own website and are using our address for deposits, the appropriate approach would be to manage your own user addresses, ledger information, and so on, to keep track of users' deposit records. Then, you should consolidate the funds and transfer them to the KuCoin account
Besides that,, you can create multiple sub-accounts, with each account having a different address.
