### ISSUE TITLE
How to get all (historical) trades/actions

### ISSUE THREAD

**Issue by bernhardh** [Kucoin/kucoin-php-sdk#118]
How can I get all finished trades/actions with this api?

**Comment by codewc** [comment]
use `GET /api/v1/fills` endpoint

Data time range

The system allows you to retrieve data up to one week (start from the last day by default). If the time period of the queried data exceeds one week (time range from the start time to end time exceeded 7*24 hours), the system will prompt to remind you that you have exceeded the time limit. If you only specified the start time, the system will automatically calculate the end time (end time = start time + 7 * 24 hours). On the contrary, if you only specified the end time, the system will calculate the start time (start time= end time - 7 * 24 hours) the same way.

Refer to: https://docs.kucoin.com/#list-fills

**Comment by bernhardh** [comment]
Thanks for your feedback! I found this already, but didn't get any data. Possible because there are no actions the last 7 days. 

So there is no chance to get the full history?

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
