### ISSUE TITLE
Issue with GuzzleHttp\Psr7\uri_for() function at WebSocketFeed

### ISSUE THREAD

**Issue by mkmnstr123** [Kucoin/kucoin-php-sdk#119]
There is a problem with the GuzzleHttp library. It needs to be updated on the component! It crashes very badly!

[2021-12-22 09:36:04] production.ERROR: Call to undefined function GuzzleHttp\Psr7\uri_for() {"exception":"[object] (Error(code: 0): Call to undefined function GuzzleHttp\\Psr7\\uri_for() at /var/app/current/vendor/ratchet/pawl/src/Connector.php:126)
[stacktrace]
#0 /var/app/current/vendor/ratchet/pawl/src/Connector.php(38): Ratchet\\Client\\Connector->generateRequest('wss://ws-api.ku...', Array, Array)
#1 /var/app/current/vendor/kucoin/kucoin-php-sdk/src/PrivateApi/WebSocketFeed.php(138): Ratchet\\Client\\Connector->__invoke('wss://ws-api.ku...')
#2 /var/app/current/vendor/kucoin/kucoin-php-sdk/src/PrivateApi/WebSocketFeed.php(229): KuCoin\\SDK\\PrivateApi\\WebSocketFeed->subscribeChannels(Array, Array, Object(Closure), NULL, Array)

**Comment by Parsoolak** [comment]
```
"ratchet/rfc6455": "^0.3",
"guzzlehttp/psr7": "^1.8.2"
````
Add Them to your composer.json and update composers and done :)

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
