### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by bugbaal** [Kucoin/kucoin-php-sdk#123]
Is there a way to add subscription without restart the call?
In the same way the createUnsubscribeMessage does.
Thanks

**Comment by hhxsv5** [comment]
Please upgrade sdk to [v1.1.27](https://github.com/Kucoin/kucoin-php-sdk/releases/tag/v1.1.27).

```php
// Subscribe another channel
$ws->send(json_encode($api->createSubscribeMessage('/market/ticker:LTC-BTC')));
```
