### ISSUE TITLE
quantity increment is invalid when trying to trailing sell

### ISSUE THREAD

**Issue by abda11ah** [Kucoin/kucoin-php-sdk#133]
Hi,
I get an error 400100 when i try to sell SMOLE coins
I don't know what I have to do to launch my trailing sell order.

![Screenshot_20240331-055954_KuCoin](https://github.com/Kucoin/kucoin-php-sdk/assets/1699034/141f1a96-1e23-41cd-8473-c6de835774a3)

pls help

**Comment by 435844292** [comment]
Hi:

Spot:

Please refer to this interface, GET /api/v2/symbols

Price precision: priceIncrement, the price of the order must be a positive integer multiple of the price increment (if the increment is 0.01, the request for the order price is 0.001 or 0.021 will be rejected and invalid priceIncrement will be returned)

Quantity precision of market order: quoteIncrement, funds increment, the funds of the order must be a positive integer multiple of the funds increment

Quantity precision: baseIncrement, amount increment, the size of the order must be a positive integer multiple of the amount increment

Future:

​Please refer to this interface, GET /api/v1/contracts/{symbol}

Price precision: tickSize

Amount precision: lotSize, The trade amount indicates the amount of contract to buy or sell, and contract uses the base currency or lot as the trading unit. The trade amount must be no less than 1 lot for the contract and no larger than the maxOrderQty. It should be a multiple number of the lot, or the system will report an error when you place the order. E.g. 1 lot of XBTUSDTM is 0.001 Bitcoin, while 1 lot of XBTUSDM is 1 USD.

Margin:

The precision of the amount of margin loans:

At present, the minimum repayment amount of a single transaction should be >= currency precision, for example, the precision of ETH is 0.00000001, and the minimum repayment amount is 0.00000001

The minimum loan amount for a single transaction is currently not available on the official endpoint, you can query through this interface

https://www.kucoin.com/_api/margin-config/loan-currencies

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
