### ISSUE TITLE
Compatibility issue on Windows

### ISSUE THREAD

**Issue by schuesslerf** [Kucoin/kucoin-php-sdk#35]
Hello,

I just tried implementing your basic example for getting the list of wallets (using the code of your "Account.php".

Now when I try to run it, I get this error:

`string(236) "[HTTP]Failure: status code is NOT 200, GET /api/v1/accounts?type=main with body=[], respond code=400 body={"code":"400001","msg":"Please check the header of your request for KC-API-KEY, KC-API-SIGN, KC-API-TIMESTAMP, KC-API-PASSPHRASE"}"`

The docs say that:

All REST requests must contain the following headers:

KC-API-KEY The api key as a string.
KC-API-SIGN The base64-encoded signature (see Signing a Message).
KC-API-TIMESTAMP A timestamp for your request.
KC-API-PASSPHRASE The passphrase you specified when creating the API key.

Does this mean, that your sdk is not working anymore, because I can't to the message signing thing?

**Comment by hhxsv5** [comment]
It works for me, what version of sdk do you use?

**Comment by schuesslerf** [comment]
Hello,

I have the same version as you got...

```
{
            "name": "kucoin/kucoin-php-sdk",
            "version": "v1.0.11",
            "source": {
                "type": "git",
                "url": "https://github.com/Kucoin/kucoin-php-sdk.git",
                "reference": "42d606d189b2e6afebe624ba3b40bc8b19458ea9"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/Kucoin/kucoin-php-sdk/zipball/42d606d189b2e6afebe624ba3b40bc8b19458ea9",
                "reference": "42d606d189b2e6afebe624ba3b40bc8b19458ea9",
                "shasum": ""
            },
            "require": {
                "ext-json": "*",
                "guzzlehttp/guzzle": "~6.0",
                "php": ">=5.5.0",
                "ratchet/pawl": "^0.3.2"
            },
            "require-dev": {
                "phpunit/phpunit": "^5.7"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "KuCoin\\SDK\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "KuCoin",
                    "email": "php@kucoin.com"
                }
            ],
            "description": "PHP SDK for KuCoin API",
            "homepage": "https://github.com/Kucoin/kucoin-php-sdk",
            "keywords": [
                "api",
                "kucoin",
                "sdk"
            ],
            "time": "2019-03-22T05:10:40+00:00"
        },
```
Thats the complete code I use:

```
<?php

require 'vendor/autoload.php';

use KuCoin\SDK\Auth;
use KuCoin\SDK\KuCoinApi;
use KuCoin\SDK\PrivateApi\Account;
use KuCoin\SDK\Exceptions\HttpException;
use KuCoin\SDK\Exceptions\BusinessException;

KuCoinApi::setBaseUri('https://openapi-v2.kucoin.com');

$auth = new Auth('12345', '12345', 'myBestPassword');
$api = new Account($auth);
try {
    $result = $api->getList(['type' => 'main']);
    var_dump($result);
} catch (HttpException $e) {
    var_dump($e->getMessage());
} catch (BusinessException $e) {
    var_dump($e->getMessage());
}
?>
```

I'm normally using XAMPP to run the script directly in browser, but just to double check I also tried running it with the direct php command, resulting in the same error:

```
C:\xampp\htdocs\kucoin>C:\xampp\php\php.exe getKucoinBalance.php
string(236) "[HTTP]Failure: status code is NOT 200, GET /api/v1/accounts?type=main with body=[], respond code=400 body={"code":"400001","msg":"Please check the header of your request for KC-API-KEY, KC-API-SIGN, KC-API-TIMESTAMP, KC-API-PASSPHRASE"}"
```

Any other ideas about the problem..?

**Comment by hhxsv5** [comment]
A little weird, I have no idea. 
And I uploaded a zip file, please try it [test.tar.gz](https://github.com/Kucoin/kucoin-php-sdk/files/3008863/test.tar.gz).

**Comment by schuesslerf** [comment]
Me neitehr...

Same result with the zip:

`Fatal error: Uncaught KuCoin\SDK\Exceptions\HttpException: [HTTP]Failure: status code is NOT 200, GET /api/v1/accounts?type=main with body=[], respond code=400 body={"code":"400001","msg":"Please check the header of your request for KC-API-KEY, KC-API-SIGN, KC-API-TIMESTAMP, KC-API-PASSPHRASE"} in C:\xampp\htdocs\test\vendor\kucoin\kucoin-php-sdk\src\Http\ApiResponse.php:69 Stack trace: #0 C:\xampp\htdocs\test\vendor\kucoin\kucoin-php-sdk\src\Http\ApiResponse.php(99): KuCoin\SDK\Http\ApiResponse->mustSuccessful() #1 C:\xampp\htdocs\test\vendor\kucoin\kucoin-php-sdk\src\PrivateApi\Account.php(41): KuCoin\SDK\Http\ApiResponse->getApiData() #2 C:\xampp\htdocs\test\Account.php(10): KuCoin\SDK\PrivateApi\Account->getList(Array) #3 {main} thrown in C:\xampp\htdocs\test\vendor\kucoin\kucoin-php-sdk\src\Http\ApiResponse.php on line 69`

**Comment by schuesslerf** [comment]
I did fill in the keys, but same result with our without key though...

**Comment by hhxsv5** [comment]
If you didn't fill in the API Key and run it directly, it should be like this.
![image](https://user-images.githubusercontent.com/7278743/55011419-ce30f000-5020-11e9-8fc3-0b7706e9fb39.png)

**Comment by hhxsv5** [comment]
😂
Is IP the same ?
```
→ ping openapi-v2.kucoin.com
PING openapi-v2.kucoin.com (104.16.90.29): 56 data bytes
64 bytes from 104.16.90.29: icmp_seq=0 ttl=42 time=130.975 ms
64 bytes from 104.16.90.29: icmp_seq=1 ttl=42 time=130.151 ms
64 bytes from 104.16.90.29: icmp_seq=2 ttl=42 time=147.944 ms
^C
--- openapi-v2.kucoin.com ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 130.151/136.357/147.944/8.200 ms
```

**Comment by schuesslerf** [comment]
Running out of ideas..yep it is..

![image](https://user-images.githubusercontent.com/10630224/55012140-3e228480-4fe7-11e9-870c-099aa725771f.png)

**Comment by schuesslerf** [comment]
Output of the PHP file seems to be the same though, no matter if I fill in my api data or not

**Comment by hhxsv5** [comment]
Can you try to run it under Linux or OS X ?

**Comment by schuesslerf** [comment]
Sure, one sec, I'm gonna get my MacBook

**Comment by schuesslerf** [comment]
okay, now I am absolutely confused, it seems to work on the macbook, let me try pushing it on my ubuntu server

**Comment by schuesslerf** [comment]
Working on Ubuntu 16.04 and Mac OS Mojave 10.14, not working on Windows 10... First thing: Amazing, that it works now! Thanks for the help!
2nd though: Why the heck is not working on windows haha?

**Comment by hhxsv5** [comment]
I will check it on windows tomorrow.

**Comment by schuesslerf** [comment]
Sure, thank you 👍

**Comment by hhxsv5** [comment]
@schuesslerf Please tell me your version of xampp.

**Comment by hhxsv5** [comment]
@schuesslerf `composer require "kucoin/kucoin-php-sdk:~1.1.0"`
