### ISSUE TITLE
PHP Fatal error:  Uncaught RuntimeException: Unable to set stream resource to non-blocking mode

### ISSUE THREAD

**Issue by merovinh** [Kucoin/kucoin-php-sdk#68]
Hi guys!
When I try to use WebSocket feed in coroutine, I get an error:

PHP Fatal error:  Uncaught RuntimeException: Unable to set stream resource to non-blocking mode in .../vendor/react/stream/src/WritableResourceStream.php:35

```php
<?php
include_once 'vendor/autoload.php';
use KuCoin\SDK\Auth;
use KuCoin\SDK\PrivateApi\WebSocketFeed;
use Ratchet\Client\WebSocket;
use React\EventLoop\LoopInterface;

Swoole\Runtime::enableCoroutine();

$api = new WebSocketFeed(null);

$query = ['connectId' => uniqid('', true)];

$channels = [
    ['topic' => '/market/ticker:ETH-BTC'],
];

go(function() use ($api, $query, $channels) {
    $api->subscribePublicChannels($query, $channels, function (array $message, WebSocket $ws, LoopInterface $loop) {
        var_dump($message);
        $loop->stop();
    }, function ($code, $reason) {});
});

```

My OS: Centos 7
PHP 7.1.16

**Comment by userbig** [comment]
For anyone who wonders how to fix this. You need to pas 
SWOOLE_HOOK_SLEEP  or SWOOLE_HOOK_CURL into Swoole\Runtime::enableCoroutine();
https://github.com/swoole/swoole-src/issues/2969

`Swoole\Runtime::enableCoroutine(SWOOLE_HOOK_SLEEP);`

I have the same problem with running reactphp inside swoole coroutine;

**Comment by 1bazinga25** [comment]
Does this issue be solved now?

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
