### ISSUE TITLE
Bumbing guzzle

### ISSUE THREAD

**Issue by stadskle** [Kucoin/kucoin-php-sdk#97]
Any change of getting support for Guzzle HTTP 7? 

[Laravel 8](https://github.com/laravel/laravel/blob/8.x/composer.json) is now requiring Guzzle 7 ("guzzlehttp/guzzle": "^7.0.1"), and that is causing a few issues with this SDK. Currently I have downgraded Guzzle in Laravel and it seems to be working, but it would be great if the SDK could get official support for it.

**Comment by hhxsv5** [comment]
Guzzle 7.x has been supported, please upgrade SDK to v1.1.21, thank you.
