### ISSUE TITLE
Fatal error:  Uncaught Error: Class 'Swoole\Runtime' not found

### ISSUE THREAD

**Issue by itabrezshaikh** [Kucoin/kucoin-php-sdk#99]
Unfortunately this SDK does not work :(.

I tried to run sdk order method but it gave me the below error. I have installed all the dependencies using composer. My php version is 7.1.29.

```
$order = [
                'clientOid' => $order_id,
                'price'     => $price,
                'size'      => $size,
                'symbol'    => $symbol,
                'type'      => $type,
                'side'      => $side,
                'remark'    => 'ORDER#' . $order_id,
            ];
 $api = new Order($auth, new SwooleHttp);
  try {
                $result = $api->create($order);
                var_dump($result);
            } catch (\Throwable $e) {
                var_dump($e->getMessage());
            }
```

```
PHP Fatal error:  Uncaught Error: Class 'Swoole\Runtime' not found in /opt/kucoin/vendor/kucoin/kucoin-php-sdk/src/Http/SwooleHttp.php:19
Stack trace:
#0 /opt/kucoin/bot.php(60): KuCoin\SDK\Http\SwooleHttp->__construct()
#1 {main}
  thrown in /opt/kucoin/vendor/kucoin/kucoin-php-sdk/src/Http/SwooleHttp.php on line 19

```

**Comment by hhxsv5** [comment]
Is the Swoole extension installed successfully?  try `php --ri swoole`.

**Comment by itabrezshaikh** [comment]
Thank you for the help, it worked after installing 
```
pecl install swoole
```
However later it gave another dependency error:
 "Class 'Swlib\Saber' not found"

Which got fixed after.
php composer.phar require swlib/saber

Also, I was able to install this only on PHP 7.2+

Now, its working.

I guess all these things should be updated on readme or docs.

**Comment by hhxsv5** [comment]
[Reference documents](https://github.com/Kucoin/kucoin-php-sdk#%EF%B8%8Fcoroutine-http-client-for-asynchronous-io)
